---

apt:
  autoremove: yes
  autoclean: yes
  update_cache: yes
  cachetime: 3600
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
dotfiles:
  repourl: git@github.com:paulmallon/cfg.git

  