---

healthcheck_uuid: 9e58a7b9-29e4-42f0-94a6-c780e52439c7

system:
  swappiness_value: 20

apt:
  autoremove: yes
  autoclean: yes
  update_cache: yes
  cachetime: 3600

ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false

dotfiles:
  repourl: git@github.com:paulmallon/cfg.git

ansible:
  repourl: git@github.com:paulmallon/ansible-ubuntu.git
  user: pm 
  ansible_cron_minute: 5
