---

#
# Pre tasks
#
- hosts: all
  tags: always
  become: true
  pre_tasks:
#    - name: "pre-run | Load variables from 'host_vars/{{ansible_hostname}}.yml'"
#      include_vars:
#        file: "host_vars/{{ansible_hostname}}.yml"

    - name: pre-run | Update apt cache 
      tags: always
      apt: 
        update_cache: '{{ apt.update_cache }}'
      changed_when: False

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
#
# Roles
#
- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation

#
# Post tasks
#
- hosts: all
  become: true
  tasks:
  - name: post-run | Cleanup apt cache and remove orphan packages 
    tags: always
    apt:
      autoclean: '{{ apt.update_cache }}'
      autoremove: '{{ apt.autoremove }}'
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: post-run | Send completion alert
    tags: always
    uri:
      url: https://hc-ping.com/{{ healthcheck_uuid }}
    changed_when: False
    when:
      - task_failed is not defined
      - healthcheck_uuid is defined

  - name: post-run | Send failure alert
    tags: always
    uri:
      url: https://hc-ping.com/{{ healthcheck_uuid }}/fail
    when:
      - task_failed is defined
      - task_failed == true
