---

- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update apt cache 
      tags: always
      apt: 
        update_cache: '{{ apt.update_cache }}'
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: all
  tags: workstation
  become: true
  roles:
    - workstation

- hosts: all
  become: true
  tasks:
  - name: post-run | cleanup apt cache and remove orphan packages 
    tags: always
    apt:
      autoclean: '{{ apt.update_cache }}'
      autoremove: '{{ apt.autoremove }}'
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: post-run | send completion alert
    tags: always
    uri:
      url: https://hc-ping.com/{{ healthcheck_uuid }}
    changed_when: False
    when:
      - task_failed is not defined
      - healthcheck_uuid is defined

 - name: post-run | send failure alert
    tags: always
    uri:
      url: https://hc-ping.com/{{ healthcheck_uuid }}/fail
    when:
      - task_failed is defined
      - task_failed == true
