---

- name: Clone bare repository to ~/.cfg
  ansible.builtin.git:
    repo: '{{ dotfiles.repourl }}'
    dest: "{{ lookup('env','HOME') }}/.cfg"
    bare: yes

- name: Configure status showUntrackedFiles no
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config status.showUntrackedFiles no

- name: Checkout repository 
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout --force
