---

#
# sudoers
#
- name: "users | sudoers |  Add '{{ lookup('env', 'USER') }}' sudoers file"
  tags: pm,sudoers,users
  copy:
    dest: "/etc/sudoers.d/{{ lookup('env', 'USER') }}"
    owner: root
    group: root
    mode: 0440
    content: |
      {{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: ALL

#
# ssh
#        
- name: "users | ssh-keys | Create '{{ lookup('env','HOME') }}/.ssh directory'"
  tags: pm,ssh,users
  file:
    path: "{{ lookup('env','HOME') }}/{{ item.dir }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0700
  with_items:
    - { dir: '.ssh' }

- name: "users | ssh-keys | Add 'pm_id_20210321.pub' to autorized keys"
  tags: pm,ssh,ssh-keys,users
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ item }}"
  with_file:
    - pm_id_20210321.pub

- name: "users | ssh-keys | Generate SSH key '{{ lookup('env','HOME') + '/.ssh/id_rsa' }}'"
  tags: pm,ssh,ssh-keys,users
  openssh_keypair:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: "users | ssh-keys | Ensure authorized keys contains '{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}' "
  tags: pm,ssh,ssh-keys,users
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    state: present

- name: "users | ssh-keys | Ensure '0755' permissions on directory '{{ lookup('env','HOME') + '/.ssh/' }}'"
  tags: pm,ssh,ssh-keys,users
  file:
    path: "{{ lookup('env','HOME') + '/.ssh' }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0755

- name: "users | ssh-keys | Ensure '0644' permissions on file '{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}'"
  tags: pm,ssh,ssh-keys,users
  file:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0644

- name: "users | ssh-keys | Ensure '0644' permissions on file '{{ lookup('env','HOME') + '/.ssh/authorized_keys' }}'"
  tags: pm,ssh,ssh-keys,users
  file:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0644

#
# git
#

- name: "users | git | Create '{{ lookup('env','HOME') }}/git directory'"
  tags: pm,ssh,users
  file:
    path: "{{ lookup('env','HOME') }}/{{ item.dir }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0700
  with_items:
    - { dir: 'git' }

- name: "users | git | Configure git pull '{{ git.pull }}'"
  become: false
  tags: pm,git,users
  shell: "git config --global pull.{{ git.pull }}"

- name: "users | git | Configre git user '{{ git.user }}'"
  become: false
  tags: pm,git,users
  shell: "git config --global user.name '{{ git.user }}' --replace-all"

- name: "users | git | Configre git email '{{ git.email }}'"
  become: false
  tags: pm,git,users
  shell: "git config --global user.email {{ git.email }}"

- name: "users | git | Configure git push.default '{{ git.push }}'"
  become: false
  tags: pm,git,users
  shell: "git config --global push.default {{ git.push }}"

#
# dofiles
#
- name: "users | dotfiles | Clone bare repository from '{{ dotfiles.repourl }}' to '{{ lookup('env','HOME') }}/.cfg'"
  tags: pm,dotfiles,users
  ansible.builtin.git:
    repo: '{{ dotfiles.repourl }}'
    dest: "{{ lookup('env','HOME') }}/.cfg"
    bare: yes
  become: no

- name: "users | dotfiles | Configure repository with 'showUntrackedFiles no'"
  tags: pm,dotfiles,users
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config status.showUntrackedFiles no
  become: no

- name: "users | dotfiles | Force checkout repository"
  tags: pm,dotfiles,users
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout --force
  become: no



