---


#
# sudoers
#
- name: "users | sudoer |  Add '{{ lookup('env', 'USER') }}' sudoers file"
  tags: pm,ssh,ssh-keys,users
  copy:
    dest: "/etc/sudoers.d/{{ lookup('env', 'USER') }}"
    owner: root
    group: root
    mode: 0440
    content: |
      {{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: ALL

#
# ssh
#        
- name: "users | ssh | Create .ssh directory"
  tags: pm,ssh,users
  file:
    path: "{{ lookup('env','HOME') }}/{{ item.dir }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0700
  with_items:
    - { dir: '.ssh' }

- name: "users | ssh | Add 'pm_id_20210321.pub' to autorized keys"
  tags: pm,ssh,ssh-keys,users
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ item }}"
  with_file:
    - users/pm_id_20210321.pub

- name: "users | ssh | Generate SSH key '{{ lookup('env','HOME') + '/.ssh/id_rsa' }}'"
  tags: pm,ssh,ssh-keys,users
  openssh_keypair:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: "users | ssh | Ensure authorized key contains '{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}' "
  tags: pm,ssh,ssh-keys,users
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    state: present

- name: "users | ssh | Ensure file permissions on '{{ lookup('env','HOME') + '/.ssh/' }}'"
  tags: pm,ssh,ssh-keys,users
  file:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0755

- name: "users | ssh | Ensure file permissions on '{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}'"
  tags: pm,ssh,ssh-keys,users
  file:
    path: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0644

#
# git
#
- name: "users | git | Configure git pull. {{ git.pull }}"
  tags: pm,git,users
  shell: "git config --global pull.{{ git.pull }}"

- name: "users | git | Configre git user '{{ git.user }}'"
  tags: pm,git,users
  shell: "git config --global user.name '{{ git.user }}' --replace-all"

- name: "users | git | Configre git email '{{ git.email }}'"
  tags: pm,git,users
  shell: "git config --global user.email {{ git.email }}"

- name: "users | git | Configure git push.default '{{git.push }}'"
  tags: pm,git,users
  shell: "git config --global push.default {{ git.push }}"

#
# xfce4 shortcuts
#

- name: users | xfce4 | general | Set number of workspaces (2)
  tags: pm,xfce4,users,workspace 
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: /general/workspace_count
    value_type: int
    value: "2"

- name: users | xfce4 | shortcut | Remove '<Alt>F12' keybinding
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<Alt>F12"
    value_type: string
    value: "null"

- name: users | xfce4 | shortcut | code
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>e"
    value_type: string
    value: "code"

- name: users | xfce4 | shortcut | thunar
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>f"
    value_type: string
    value: "thunar"


- name: users | xfce4 | shortcut | firefox
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>w"
    value_type: string
    value: "firefox"

- name: users | xfce4 | shortcut | xfce4-display-settings
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>p"
    value_type: string
    value: "xfce4-display-settings --minimal"

- name: users | xfce4 | shortcut | xfce4-appfinder
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>r"
    value_type: string
    value: "xfce4-appfinder"

- name: users | xfce4 | shortcut | xfce4-terminal
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/default/<super>r"
    value_type: string
    value: "xfce4-terminal --tab"

- name: users | xfce4 | shortcut | tile_down_left_key
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/custom/<Primary><Super>Left"
    value_type: string
    value: "tile_down_left_key"


- name: users | xfce4 | shortcut | tile_down_right_key
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/custom/<Primary><Super>Right"
    value_type: string
    value: "tile_down_right_key"

- name: users | xfce4 | shortcut | tile_up_left_key
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/custom/<Shift><Super>Left"
    value_type: string
    value: "tile_up_left_key"

- name: users | xfce4 | shortcut | tile_up_right_key
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: "/custom/<Shift><Super>Right"
    value_type: string
    value: "tile_up_right_key"

#
# dofiles
#

- name: "dotfiles | Clone bare repository to ~/.cfg from '{{ dotfiles.repourl }}'"
  tags: pm,dotfiles,config,users
  ansible.builtin.git:
    repo: '{{ dotfiles.repourl }}'
    dest: "{{ lookup('env','HOME') }}/.cfg"
    bare: yes
  become: no

- name: "dotfiles | Configure 'status showUntrackedFiles no'"
  tags: pm,dotfiles,config,users
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config status.showUntrackedFiles no
  become: no

- name: "dotfiles | Checkout repository"
  tags: pm,dotfiles,config,users
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout --force
  become: no

