---

- name: software | code | Add Micorsoft Apt Keys
  tags: code, dev, software
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: software.code is defined and software.code == true

- name: software | code | Add Visual Studio Code repository
  tags: code, dev, software
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
  when: software.code is defined and software.code == true
  
- name: software | code | Install Visual Studio Code
  tags: code, dev, software
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - code
  when: software.code is defined and software.code == true

- name: software | code | Set Code as default editor 
  tags: code, dev, software
  alternatives:
    name: editor
    path: /usr/bin/code
  when: software.code is defined and software.code == true