- name: software | cpupower-gui | Install cpupower-gui
  tags: cpupower-gui,cpupower,software
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - cpupower-gui
  when: software.cpupower is defined and software.cpupower == true
