---

- name: software | java | Install OpenJDK 15
  tags: dev, java, software
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - openjdk-15-jre
      - openjdk-15-jdk
  when: software.java is defined and software.java == true
    
    
    
