---

- name: software | remmina | Install Remmina
  tags: remmina, software
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - remmina
  when: software.remmina is defined and software.remmina == true
