- name: software | solaar | Install Solaar
  tags: solaar, software
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - solaar
  when: software.solaar is defined and software.solaar == true

- name: software | solaar | Make sure solaar doesn't autostart
  tags: solaar, software
  file:
    path: /etc/xdg/autostart/solaar.desktop
    state: absent
  when: software.solaar is defined and software.solaar == true