---


- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW and deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming