---

- name: system config | memory | Set swappiness to '{{ system.swappiness_value }}'
  tags: swappiness,sysctl,memory,config,system
  lineinfile:
    dest: "/etc/sysctl.conf"
    create: yes
    regexp: "swappiness ="
    line: "vm.swappiness = 5"
  register: swappiness

- name: system config | memory | apply swappiness
  tags: swappiness,sysctl,memory,config,system
  command: sysctl vm.swappiness={{ system.swappiness_value }}
  when: swappiness.changed
