---

- name: "system config | ssh-server | {{ ssh.password_auth | ternary('Allow','Disallow') }} password authentication"
  tags: ssh-server,config,system,ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication {{ ssh.password_auth | ternary('yes','no') }}"
    state: present
    backup: yes
  notify:
    - restart ssh
    
- name: "system config | ssh-server | {{ ssh.root_login | ternary('Allow','Disallow') }} root SSH access"
  tags: ssh-server,config,system,ssh
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin {{ ssh.root_login | ternary('yes','no') }}"
        state: present
        backup: yes
  notify:
    - restart ssh

- name: "system config | ssh-server | Ensure SSH service state is {{ ssh.start | ternary('started','stopped') }}"
  tags: ssh-server,config,system,ssh
  ansible.builtin.service:
    name: ssh
    state: "{{ ssh.start | ternary('restarted','stopped') }}"
    enabled: "{{ ssh.service_enabled }}"
