---

- name: "system setup | ufw | Allow SSH connections"
  tags: ufw,config,system,setup
  ufw:
    rule: allow
    name: OpenSSH

- name: "system setup | ufw | Enable UFW and deny all other incoming traffic by default"
  tags: ufw,config,system,setup
  ufw:
    state: enabled
    policy: deny
    direction: incoming