---

- name: Install Java 15 JDK and JRE
  apt:
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: '{{ aptcachetime }}'
    state: latest
    pkg:
      - openjdk-15-jre
      - openjdk-15-jdk
    
    
    
