---

- name: Install Java 15 JDK and JRE
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    autoclean: '{{ apt.autoclean }}'
    autoremove: '{{ apt.autoremove }}'
    update_cache: '{{ apt.update_cache }}'
    pkg:
      - openjdk-15-jre
      - openjdk-15-jdk
    
    
    
