---

- name: "software | common | Install common apt packages"
  tags: software,common,apt
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - build-essential
      - curl
      - diffutils
      - git
      - grep
      - gzip
      - htop
      - iotop
      - less
      - make
      - nano
      - nmap
      - openssl
      - rar
      - rsync
      - software-properties-common
      - tar
      - unzip
      - vim
      - wget
      - whois
      - zip
      - stress
      - s-tui
      - iputils-ping 
      - net-tools
      - powertop
      - nmon
      - iptraf-ng
      - jq
      - dnsutils      
      - nomad
      - lm-sensors
      - tldr
      - dos2unix
      - libxml2-utils

- name: "software | common | Install common pip packages"
  tags: software,common,pip
  pip:
    name: Pygments

- name: "software | common | Install OpenSSH server"
  tags: ssh-server, config, ssh
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    pkg:
      - openssh-server
  notify:
    - restart ssh

