---

- name: Update Apt cache
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    cache_valid_time: '{{ aptcachetime }}'
    state: latest
    pkg:
      - build-essential
      - curl
      - diffutils
      - git
      - grep
      - gzip
      - htop
      - iotop
      - less
      - make
      - nano
      - nmap
      - openssl
      - rar
      - rsync
      - software-properties-common
      - tar
      - unzip
      - vim
      - wget
      - whois
      - zip
      - stress
      - s-tui
      - iputils-ping 
      - net-tools
      - powertop
      - nmon
      - iptraf-ng
      - jq
      - dnsutils
      - solaar
      - cpupower-gui
      - nomad

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    
