---

- name: Install packages
  apt:
    state: latest
    cache_valid_time: '{{ apt.cachetime }}'
    autoclean: '{{ apt.autoclean }}'
    autoremove: '{{ apt.autoremove }}'
    update_cache: '{{ apt.update_cache }}'
    pkg:
      - build-essential
      - curl
      - diffutils
      - git
      - grep
      - gzip
      - htop
      - iotop
      - less
      - make
      - nano
      - nmap
      - openssl
      - rar
      - rsync
      - software-properties-common
      - tar
      - unzip
      - vim
      - wget
      - whois
      - zip
      - stress
      - s-tui
      - iputils-ping 
      - net-tools
      - powertop
      - nmon
      - iptraf-ng
      - jq
      - dnsutils
      - solaar
      - cpupower-gui
      - nomad

- name: "Configure git pull.{{ git.pull }}"
  shell: "git config --global pull.{{ git.pull }}"

- name: "Configre git user {{ git.user }} "
  shell: "git config --global user.name {{ git.user }}"

- name: "Configre git email {{ git.user }}"
  shell: "git config --global user.email {{ git.user }}"

- name: "Configure git push.default {{git.push }}"
  shell: "git config --global push.default {{ git.push }}"