---

git:
  user: "PM"
  email: "paul.james.mallon@gmail.com"
  pull: "ff only"
  push: upstream
system:
  swappiness_value: 10
  provisioning: true
software: 
  code: true
  intellij: true
  java: true
  signal: true
  spotify: true
  teams: true
  solaar: true
  remmina: true
  cpupower: true
xfce:
  install_panel: true
  panel_backup: default_panel.tar
  spotify_panel_repo_url: git@github.com:paulmallon/xfce4-spotify-panel.git
  install_terminal_theme: true
  terminal_theme_repo_url: git@github.com:arcticicestudio/nord-xfce-terminal.git