---

apt:
  autoremove: yes
  autoclean: yes
  update_cache: yes
  cachetime: 3600
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
dotfiles:
  repourl: git@github.com:paulmallon/cfg.git
git:
  user: "Paul Mallon"
  email: "paul.mallon@pricerunner.com"
  pull: "ff only"
  push: upstream
ansible:
  repourl: git@github.com:paulmallon/ansible-ubuntu.git
  user: pm 
  ansible_cron_minute: 5