---


#
# Restore panel layout
#
- name: "xfce4 | panel | Stop xfce4-panel"
  become: false
  tags: pm,xfce4,panel,users
  shell: "xfce4-panel -q"
  when: xfce.install_panel is defined and xfce.install_panel == true
  ignore_errors: yes
 
- name: xfce4 | panel | Copy panel backup '{{ xfce.panel_backup }}' to /tmp
  tags: pm,xfce4,panel,users
  become: false
  copy:
    src: "{{ xfce.panel_backup }}"
    dest: /tmp
  when: xfce.install_panel is defined and xfce.install_panel == true
  ignore_errors: yes

- name: "xfce4 | panel | Restore panel layout from '/tmp/{{ xfce.panel_backup }}'"
  become: false
  tags: pm,xfce4,panel,users
  shell: "xfce4-panel-profiles load /tmp/{{ xfce.panel_backup }}"
  when: xfce.install_panel is defined and xfce.install_panel == true
  ignore_errors: yes


#
# Spotify panel
#

- name: "xfce4 | spotify-panel | Clone repository from '{{ xfce.spotify_panel_repo_url }}' to '{{ lookup('env','HOME') }}/git/xfce4-spotify-panel'"
  tags: pm,xfce4,panel,users
  become: false
  ansible.builtin.git:
    repo: "{{ xfce.spotify_panel_repo_url }}"
    dest: "{{ lookup('env','HOME') }}/git/xfce4-spotify-panel"
  when: xfce.install_panel is defined and xfce.install_panel == true

- name: "xfce4 | spotify-panel | Copy genmon rc backup 'genmon-6.rc' to {{ lookup('env','HOME') }}/.config/xfce4/panel/genmon-6.rc"
  tags: pm,xfce4,panel,users
  become: false
  copy:
    src: "genmon-6.rc"
    dest: "{{ lookup('env','HOME') }}/.config/xfce4/panel/genmon-6.rc"
  when: xfce.install_panel is defined and xfce.install_panel == true
  
- name: "xfce4 | spotify-panel | Set Command"
  tags: pm,xfce4,panel,users
  lineinfile: 
    dest: "{{ lookup('env','HOME') }}/.config/xfce4/panel/genmon-6.rc"
    regexp: ^Command=
    line: Command=/home/pm/git/xfce4-spotify-panel/spotify-panel.sh 
  when: xfce.install_panel is defined and xfce.install_panel == true

- name: "xfce4 | spotify-panel | Set UseLabel"
  tags: pm,xfce4,panel,users
  lineinfile: 
    dest: "{{ lookup('env','HOME') }}/.config/xfce4/panel/genmon-6.rc"
    regexp: ^UseLabel=
    line: UseLabel=0
  when: xfce.install_panel is defined and xfce.install_panel == true

- name: "xfce4 | spotify-panel | Set UpdatePeriod"
  tags: pm,xfce4,panel,users
  lineinfile: 
    dest: "{{ lookup('env','HOME') }}/.config/xfce4/panel/genmon-6.rc"
    regexp: ^UpdatePeriod=
    line: UpdatePeriod=5000
  when: xfce.install_panel is defined and xfce.install_panel == true



#
# Start panel
#

- name: "xfce4 | panel | Start xfce4-panel"
  become: false
  tags: pm,xfce4,panel,users
  shell: "nohup xfce4-panel &"
  when: xfce.install_panel is defined and xfce.install_panel == true
  ignore_errors: yes