---

#
# xfce4 workspace
#
- name: xfce4 | workspace | Set number of workspaces (2)
  tags: pm,xfce4,users,workspace 
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfwm4
    property: /general/workspace_count
    value_type: int
    value: "2"

#
# xfce4 shortcuts
#
- name: xfce4 | shortcut | Remove '/commands/custom/<Primary><Alt>l' 
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Primary><Alt>l"
    state: absent
    value: notset
    value_type: string

- name: xfce4 | shortcut | Remove '/commands/default/<Primary><Alt>l' 
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/default/<Primary><Alt>l"
    state: absent
    value: notset
    value_type: string

- name: xfce4 | shortcut | Remove '/xfwm4/default/<Alt>F12' 
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/default/<Alt>F12"
    state: absent
    value: notset
    value_type: string

- name: xfce4 | shortcut | Remove '/xfwm4/custom/<Alt>F12'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/<Alt>F12"
    state: absent
    value: notset
    value_type: string


- name: xfce4 | shortcut | Code '<Super>e' 
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>e"
    value_type: string
    value: "code"

- name: xfce4 | shortcut | Thunar '<Super>f'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>f"
    value_type: string
    value: "thunar"

- name: xfce4 | shortcut | firefox '<Super>W'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>w"
    value_type: string
    value: "firefox"

- name: xfce4 | shortcut | xfce4-display-settings '<Super>p'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>p"
    value_type: string
    value: "xfce4-display-settings --minimal"

- name: xfce4 | shortcut | xfce4-appfinder '<Super>r'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>r"
    value_type: string
    value: "xfce4-appfinder"

- name: xfce4 | shortcut | xflock4 '<Super>l'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>l"
    value_type: string
    value: "xflock4"

- name: xfce4 | shortcut | xflock4 '<Primary><Alt>Delete'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Primary><Alt>Delete"
    value_type: string
    value: "xflock4"
  
- name: xfce4 | shortcut | xfce4-terminal --tab '<Super>t'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/<Super>t"
    value_type: string
    value: "xfce4-terminal --tab"

- name: xfce4 | shortcut | xfce4-terminal --drop-down 'F1'
  tags: pm,xfce4,users,shortcuts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/F1"
    value_type: string
    value: "xfce4-terminal --drop-down"


#
# xfce4 window shortcuts
#
- name: xfce4 | shortcut | tile_down_left_key '<Primary><Super>Left'
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/<Primary><Super>Left"
    value_type: string
    value: "tile_down_left_key"


- name: xfce4 | shortcut | tile_down_right_key '<Primary><Super>Right'
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/<Primary><Super>Right"
    value_type: string
    value: "tile_down_right_key"

- name: xfce4 | shortcut | tile_up_left_key '<Shift><Super>Left'
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/<Shift><Super>Left"
    value_type: string
    value: "tile_up_left_key"

- name: xfce4 | shortcut | tile_up_right_key '<Shift><Super>Right'
  tags: pm,xfce4,users,shortcut
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/<Shift><Super>Right"
    value_type: string
    value: "tile_up_right_key"


#
# fonts
#


- name: xfce4 | xsettings | FontName 'Noto Sans 9'
  tags: pm,xfce4,users,fonts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xsettings
    property: "/Gtk/FontName"
    value_type: string
    value: "Noto Sans 9"


- name: xfce4 | xsettings | MonospaceFontName 'Monospace 10'
  tags: pm,xfce4,users,fonts
  become_user: pm
  environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  xfconf:
    channel: xsettings
    property: "/Gtk/MonospaceFontName"
    value_type: string
    value: "Monospace 10"


  #