---

- name: provisioning | Ensure ansible is the latest version
  tags: provisioning,ansible
  package:
    name: ansible
    state: latest
  when: system.provisioning is defined and system.provisioning == true

- name: provisioning | Generate provision script from template
  tags: provisioning,ansible,scripts
  template:
    src: provision.sh.j2
    dest: /usr/local/bin/provision
    owner: root
    group: root
    mode: 0755
  when: system.provisioning is defined and system.provisioning == true

- name: provisioning | Install cron package
  tags: provisioning,ansible,ansible-cron,cron
  package:
    name:
      - "cron"
    state: latest
  when: system.provisioning is defined and system.provisioning == true

- name: provisioning | Schedule automatic ansible provisioning
  tags: provisioning,ansible,ansible-cron,cron
  cron:
    name: "ansible provision"
    user: pm
    hour: "{{ ansible.ansible_cron_hour | default('*/12') }}"
    minute: "{{ ansible.ansible_cron_minute | default('0') }}"
    job: "/usr/local/bin/provision > /dev/null"
  when: system.provisioning is defined and system.provisioning == true

- name: provisioning | Schedule ansible pull cleanup at boot
  tags: provisioning,ansible,ansible-cron,cron
  cron:
    name: "ansible refresh at boot"
    user: pm
    special_time: reboot
    job: "/bin/rm -rf /home/pm/.ansible/pull"
  when: system.provisioning is defined and system.provisioning == true